# Generated by Django 5.1.7 on 2025-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DR", "Debit"), ("CR", "Credit")], max_length=2
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
    ]
