# Generated by Django 5.1.7 on 2025-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_profile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlybudget",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="current_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
