# Generated by Django 5.1.7 on 2025-03-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_monthlybudget_monthly_budget_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("DR", "Debit"), ("CR", "Credit")], max_length=2
                    ),
                ),
                (
                    "date",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Day 1"),
                            (2, "Day 2"),
                            (3, "Day 3"),
                            (4, "Day 4"),
                            (5, "Day 5"),
                            (6, "Day 6"),
                            (7, "Day 7"),
                            (8, "Day 8"),
                            (9, "Day 9"),
                            (10, "Day 10"),
                            (11, "Day 11"),
                            (12, "Day 12"),
                            (13, "Day 13"),
                            (14, "Day 14"),
                            (15, "Day 15"),
                            (16, "Day 16"),
                            (17, "Day 17"),
                            (18, "Day 18"),
                            (19, "Day 19"),
                            (20, "Day 20"),
                            (21, "Day 21"),
                            (22, "Day 22"),
                            (23, "Day 23"),
                            (24, "Day 24"),
                            (25, "Day 25"),
                            (26, "Day 26"),
                            (27, "Day 27"),
                            (28, "Day 28"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
