# Generated by Django 5.1.7 on 2025-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_recurringpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalousTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance_amount", models.FloatField()),
                ("date", models.DateField()),
                ("transaction_amount", models.FloatField()),
                ("transaction_type", models.CharField(max_length=2)),
                ("recipient", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("anomaly_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
