# Generated by Django 5.1.7 on 2025-04-06 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_anomaloustransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("Stocks", "Stocks"),
                            ("Bonds", "Bonds"),
                            ("Real Estate", "Real Estate"),
                            ("Crypto", "Crypto"),
                            ("Gold", "Gold"),
                            ("Mutual Funds", "Mutual Funds"),
                            ("Money Market", "Money Market"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
